USE [master]
GO

/****** Object:  Database [dbEcellJISGrp]    Script Date: 06-08-2014 03:24:19 AM ******/
CREATE DATABASE [dbEcellJISGrp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbEcellJISGrp', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\dbEcellJISGrp.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbEcellJISGrp_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\dbEcellJISGrp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbEcellJISGrp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbEcellJISGrp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbEcellJISGrp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [dbEcellJISGrp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbEcellJISGrp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbEcellJISGrp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbEcellJISGrp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbEcellJISGrp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbEcellJISGrp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbEcellJISGrp] SET  MULTI_USER 
GO

ALTER DATABASE [dbEcellJISGrp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbEcellJISGrp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbEcellJISGrp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbEcellJISGrp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbEcellJISGrp] SET  READ_WRITE 
GO

